---
# cPanel Git Version Control Deployment Configuration
# Automates the deployment of the ST Rocketry Mission Control application
# specifically to the subdomain directory: /home/perevozk/st-rocketry-mission-control

deployment:
  tasks:
    # Указываем путь для деплоя (папка поддомена)
    - export DEPLOYPATH=/home/perevozk/st-rocketry-mission-control

    # Переходим в папку репозитория
    - echo "Navigating to repository folder..."
    - cd /home/perevozk/repositories/st-rocketry-mission-control

    # Очищаем предыдущие сборки, чтобы гарантировать свежую сборку
    - echo "Cleaning previous build artifacts..."
    - rm -rf dist/ || true
    - rm -rf node_modules/.cache || true

    # Устанавливаем зависимости проекта
    - echo "Installing project dependencies using npm..."
    - /usr/bin/npm ci --production=false

    # Собираем проект (создаёт статические файлы в папке dist)
    - echo "Building the project with npm run build..."
    - /usr/bin/npm run build

    # Проверяем успешность сборки
    - echo "Verifying that the build was successful..."
    - test -d "./dist" || (echo "Build failed: dist directory not found" && exit 1)
    - test -f "./dist/index.html" || (echo "Build failed: index.html not found" && exit 1)

    # Очищаем директорию поддомена от старых файлов
    - echo "Cleaning up old files in the deployment directory..."
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -exec rm -rf {} + || true

    # Копируем новую сборку из папки dist в директорию поддомена
    - echo "Copying new build files..."
    - /bin/cp -R ./dist/* $DEPLOYPATH/

    # Устанавливаем правильные права файлов (644 - для файлов, 755 - для папок)
    - echo "Setting proper permissions for files in deployment directory..."
    - find $DEPLOYPATH -type f -exec chmod 644 {} +
    - find $DEPLOYPATH -type d -exec chmod 755 {} +

    # Создаём файл с отметкой времени для деплоя
    - echo "Adding deployment timestamp..."
    - echo "Deployed on: $(date)" > $DEPLOYPATH/.deployment-info
    - echo "Git commit: $(git rev-parse --short HEAD)" >> $DEPLOYPATH/.deployment-info

    # Чистим ненужные файлы, чтобы избежать конфликтов
    - echo "Removing unnecessary files from deployment directory..."
    - rm -f $DEPLOYPATH/.DS_Store
    - rm -rf $DEPLOYPATH/.git*

    # Проверяем, что деплой успешно завершён
    - echo "Verifying deployment..."
    - test -f "$DEPLOYPATH/index.html" || (echo "Deployment failed: index.html not found in deployment directory" && exit 1)

    # Финальное сообщение об успешном деплое
    - echo "✅ Deployment completed successfully!"
    - echo "🚀 Application is live on the subdomain!"
    - echo "📁 Files deployed to: $DEPLOYPATH"
    - ls -la $DEPLOYPATH
