---
deployment:
  tasks:
    # Папка для выгрузки сгенерированных файлов (где находится ваш веб-сайт в cPanel)
    - export DEPLOYPATH=/home/perevozk/public_html

    # 1. Переходим в репозиторий
    - cd /home/perevozk/repositories/st-rocketry-mission-control

    # 2. Устанавливаем зависимости проекта
    - /usr/bin/npm install

    # 3. Собираем проект (папка `dist` будет содержать готовые статические файлы)
    - /usr/bin/npm run build

    # 4. Копируем содержимое папки `dist` в папку сайта
    - /bin/cp -R ./dist/* $DEPLOYPATH