---
deployment:
  tasks:
    # Указываем папку для размещения готового сборочного кода (в данном случае, public_html — это главная веб-папка сайта)
    - export DEPLOYPATH=/home/perevozk/public_html

    # Переходим в работу с репозиторием
    - cd /home/perevozk/repositories/st-rocketry-mission-control

    # Устанавливаем зависимости (если это еще не сделано)
    - /usr/bin/npm install

    # Собираем проект (сборка попадает в папку dist)
    - /usr/bin/npm run build

    # Копируем собранные файлы из папки dist в каталог для веб-размещения
    - /bin/cp -R dist/* $DEPLOYPATH

    # (Дополнительно) Убедитесь, что права доступа для сайта выставлены корректно
    - /bin/chmod -R 755 $DEPLOYPATH