---
deployment:
  tasks:
    # Указываем путь для деплоя (папка поддомена)
    - export DEPLOYPATH=/home/perevozk/st-rocketry-mission-control

    # Переходим в папку репозитория
    - echo "Navigating to repository folder..."
    - cd /home/perevozk/repositories/st-rocketry-mission-control

    # Устанавливаем зависимости
    - echo "Installing dependencies with npm..."
    - /opt/cpanel/ea-nodejs18/bin/npm ci --production=false

    # Собираем проект (создаём папку dist)
    - echo "Building the project with npm run build..."
    - /opt/cpanel/ea-nodejs18/bin/npm run build

    # Проверяем наличие папки dist перед копированием
    - echo "Verifying build output..."
    - test -d ./dist || (echo "Build failed: dist directory not found" && exit 1)
    - test -f ./dist/index.html || (echo "Build failed: index.html not found" && exit 1)

    # Копируем файлы из dist в папку поддомена
    - echo "Copying files from dist to deployment path..."
    - cp -R ./dist/* $DEPLOYPATH

    # Устанавливаем правильные права на файлы
    - echo "Setting permissions on deployed files..."
    - find $DEPLOYPATH -type f -exec chmod 644 {} +
    - find $DEPLOYPATH -type d -exec chmod 755 {} +

    # Финальное сообщение
    - echo "✅ Deployment completed successfully!"
    - echo "🚀 Application is live!"
