---
# Enhanced cPanel deployment with logging
# Automates the deployment of the ST Rocketry Mission Control application
# and saves a log of the process for debugging purposes

deployment:
  tasks:
    # Указываем путь для деплоя (папка поддомена)
    - export DEPLOYPATH=/home/perevozk/st-rocketry-mission-control

    # Переходим в папку репозитория
    - echo "Navigating to repository folder..." | tee deploy.log
    - cd /home/perevozk/repositories/st-rocketry-mission-control

    # Очищаем старые сборки (если есть)
    - echo "Cleaning previous build artifacts..." | tee -a deploy.log
    - rm -rf dist/ || true | tee -a deploy.log

    # Устанавливаем зависимости проекта
    - echo "Installing dependencies with npm..." | tee -a deploy.log
    - /usr/bin/npm ci --production=false 2>&1 | tee -a deploy.log

    # Собираем проект
    - echo "Building the project with npm run build..." | tee -a deploy.log
    - /usr/bin/npm run build 2>&1 | tee -a deploy.log

    # Проверяем наличие dist перед копированием
    - echo "Checking for dist folder..." | tee -a deploy.log
    - test -d "./dist" || (echo "Build failed: dist directory not found" && exit 1) | tee -a deploy.log
    - test -f "./dist/index.html" || (echo "Build failed: index.html not found" && exit 1) | tee -a deploy.log

    # Копируем файлы в папку поддомена
    - echo "Copying files to deployment directory..." | tee -a deploy.log
    - /bin/cp -R ./dist/* $DEPLOYPATH/ 2>&1 | tee -a deploy.log

    # Проверяем, что файлы скопировались
    - echo "Verifying deployed files..." | tee -a deploy.log
    - test -f "$DEPLOYPATH/index.html" || (echo "Deployment failed: index.html not found in deployment directory" && exit 1) | tee -a deploy.log

    # Устанавливаем правильные права на файлы
    - echo "Setting permissions on deployed files..." | tee -a deploy.log
    - find $DEPLOYPATH -type f -exec chmod 644 {} + | tee -a deploy.log
    - find $DEPLOYPATH -type d -exec chmod 755 {} + | tee -a deploy.log

    # Финальное сообщение
    - echo "✅ Deployment completed successfully!" | tee -a deploy.log
